[package]
name = "cargo-ros2"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "All-in-one build tool for ROS 2 Rust projects"

[[bin]]
name = "cargo-ros2"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
eyre = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
cargo_metadata = "0.18"
toml = "0.8"
sha2 = "0.10"

[dev-dependencies]
